**Define Rotation matrix**

*Reference: Interpretation of elements of the logarithm of a rotation matrix as rotation components around coordinate axes of a reference frame*

In [2]:
import numpy as np
def Rabg(h1, k1, l1, phi1): #Euler Rotation Matrix for Euler angles Alpha(a), Beta (b), Gamma (g)
    U = np.zeros((3, 3))
    U[0, 0] = (1-h1**2)*np.cos(phi1) + h1**2
    U[0, 1] = h1*k1*(1-np.cos(phi1)) - l1*np.sin(phi1)
    U[0, 2] = l1*h1*(1-np.cos(phi1)) + k1*np.sin(phi1)
    U[1, 0] = h1*k1*(1-np.cos(phi1)) + l1*np.sin(phi1)
    U[1, 1] = (1-k1**2)*np.cos(phi1) + k1**2
    U[1, 2] = k1*l1*(1-np.cos(phi1)) - h1*np.sin(phi1)
    U[2, 0] = l1*h1*(1-np.cos(phi1)) - k1*np.sin(phi1)
    U[2, 1] = k1*l1*(1-np.cos(phi1)) - h1*np.sin(phi1)
    U[2, 2] = (1-l1**2)*np.cos(phi1) + l1**2
    return U

**Input For Crystals**
*from https://wmich-my.sharepoint.com/:p:/r/personal/millerj_wmich_edu/Documents/WMU_Work/Research/Single_crystal_NMR/Experimental_data/8-HQ-ipc2-B_SC_NMR/WMich%20Crystal%20Orientation%20Determination.pptx?d=w5db457fa42094f38a1b5c424c418325e&csf=1&web=1&e=88dt7G*

In [5]:
phi = 27 #Rotation angle (counterclockwise direction)
phi_rad = phi*np.pi/180.0
h = 1/np.sqrt((1**2 + 0**2 + (-2)**2))
k = 0/np.sqrt((1**2 + 0**2 + (-2)**2))
l = -2/np.sqrt((1**2 + 0**2 + (-2)**2))
print(h,k,l)
R_R8HQ = Rabg(h,k,l,phi_rad)
print(R_R8HQ)

0.4472135954999579 0.0 -0.8944271909999159
[[ 0.91280522  0.40606145 -0.04359739]
 [-0.40606145  0.89100652 -0.20303072]
 [-0.04359739 -0.20303072  0.9782013 ]]


In [24]:
# R = np.zeros((3, 3))
# R[0, 0] = .5
# R[0, 1] = -0.1464
# R[0, 2] = 0.8536
# R[1, 0] = .5
# R[1, 1] = .8536
# R[1, 2] = -0.1464
# R[2, 0] = -.7071
# R[2, 1] = .5
# R[2, 2] = .5

# print(R)

**Find the angles Alpha, Beta, Gamma by which crystal is rotated**

*Reference: Computing Euler angles from a rotation matrix (Gregory G. Slabaugh)
            ; Active and Passive Rotations with Euler Angles in NMR (Millot and Man)*

Using equation 110 in Millot and Man and solving for alpha, beta and gamma

In [30]:
beta_R8HQ = np.arccos(R_R8HQ[2,2])*(180/np.pi)
alpha_R8HQ = np.arctan(R_R8HQ[1,2]/R_R8HQ[0,2])*(180/np.pi)
gamma_R8HQ = np.arctan(-R_R8HQ[2,1]/R_R8HQ[2,0])*(180/np.pi)

print('Euler angles for +8HQ_ipc2_B (alpha, beta, gamma):' , alpha_R8HQ, beta_R8HQ, gamma_R8HQ)


Euler angles for +8HQ_ipc2_B (alpha, beta, gamma): 77.8807443369023 11.985191354967485 -77.8807443369023


In [25]:
# if R[2,0] != 1 and R[2,0] != -1:
#     beta1 = -np.arcsin(R[2,0])
#     gamma1 = np.arctan((R[2,1]/np.cos(beta1))/(R[2,2]/np.cos(beta1)))
#     alpha1 = np.arctan((R[1,0]/np.cos(beta1))/(R[0,0]/np.cos(beta1)))

#     beta2 = np.pi - beta1
#     gamma2 = gamma1 - np.pi
#     alpha2 = alpha1 - np.pi
#     print('First Solution:',alpha1*180/np.pi, beta1*180/np.pi, gamma1*180/np.pi)
#     print('Second Solution:', alpha2*180/np.pi, beta2*180/np.pi, gamma2*180/np.pi)
# else:
#     alpha = 0
#     if R[2,0] == -1:
#         beta1 = np.pi/2
#         gamma1 = alpha + np.arctan(R[0,1]/R[0,2])
#     else:
#         beta2 = -np.pi/2
#         gamma2 = -alpha + np.arctan(-Rlab[0,1]/-R[0,2])
#     print('First Solution when beta = 90',alpha*180/np.pi, beta1*180/np.pi, gamma1*180/np.pi)
#     print('Second Solution when beta = 90',alpha*180/np.pi, beta2*180/np.pi, gamma2*180/np.pi)


In [4]:
# ROllett's Procedure
import numpy as np
def rollett(a, b, c, al, be, ga):
    matrix = np.zeros((3,3))
    al = np.radians(al)
    be = np.radians(be)
    ga = np.radians(ga)
    
    cosga1 = (np.cos(al)*np.cos(be) - np.cos(ga))/(np.sin(al)*np.sin(be))
    singa1 = np.sqrt((1- cosga1**2))
    matrix[0,0] = a*np.sin(be)*singa1;
    matrix[1,0] = -a*np.sin(be)*cosga1; matrix[1,1] = b*np.sin(al)
    matrix[2,0] = a*np.cos(be); matrix[2,1] = b*np.cos(al); matrix[2,2] = c
    return matrix

In [27]:
a = 1
b = 1
c = 1
alpha = 90
beta = 122.135
gamma = 90

L = rollett(a, b, c, alpha, beta, gamma)

crys_cube = np.zeros((3,3))

a = [0.92, 0.32, -0.23]
b = [-0.18, 0.88, 0.44]
c = [-0.19, -0.47, 0.86]
crys_cube[0,0] = 0.92; crys_cube[0,1] = 0.32; crys_cube[0,2] = -0.23; 
crys_cube[1,0] = -0.18; crys_cube[1,1] = 0.88; crys_cube[1,2] = 0.44; 
crys_cube[2,0] = -0.19; crys_cube[2,1] = -0.47; crys_cube[2,2] = 0.86; 

a_orth = np.matmul(L, a)
b_orth = np.matmul(L, b)
c_orth = np.matmul(L, c)

print('L:\n', L)
print('a_orth:\n', c_orth)

L:
 [[ 8.46797150e-01  0.00000000e+00  0.00000000e+00]
 [ 9.38027987e-17  1.00000000e+00  0.00000000e+00]
 [-5.31915958e-01  6.12323400e-17  1.00000000e+00]]
a_orth:
 [-0.16089146 -0.47        0.96106403]
