This code is to find Euler angles to relate crystal--> tenon frame. You need to make sure that crystal system is orthogonal. If not then conversion of oblique system to orthogonal has to be performed. Check TRAFO for the conversion

*Shiva Agarwal*

*15/November/2024*

In [2]:
import numpy as np
def get_euler_angles(a_or, b_or, c_or):
    b = np.degrees(np.arccos(c_or[2]))
    a = np.degrees(np.arctan(c_or[1]/c_or[0]))
    g = np.degrees(np.arctan(-b_or[2]/a_or[2]))

    return a, b, g

def get_direction_cosine(P, Q, R):
    

    crys_ten_a = [P[0]/np.sqrt(np.dot(P,P)), Q[0]/np.sqrt(np.dot(Q,Q)), R[0]/np.sqrt(np.dot(R,R))]

    crys_ten_b = [P[1]/np.sqrt(np.dot(P,P)), Q[1]/np.sqrt(np.dot(Q,Q)), R[1]/np.sqrt(np.dot(R,R))]

    crys_ten_c = [P[2]/np.sqrt(np.dot(P,P)), Q[2]/np.sqrt(np.dot(Q,Q)), R[2]/np.sqrt(np.dot(R,R))]

    return crys_ten_a, crys_ten_b, crys_ten_c


def rollett_matrix(a, b, c, al, be, ga):
    matrix = np.zeros((3,3))
    al = np.radians(al)
    be = np.radians(be)
    ga = np.radians(ga)
    
    cosga1 = (np.cos(al)*np.cos(be) - np.cos(ga))/(np.sin(al)*np.sin(be))
    singa1 = np.sqrt((1- cosga1**2))
    matrix[0,0] = a*np.sin(be)*singa1;
    matrix[1,0] = -a*np.sin(be)*cosga1; matrix[1,1] = b*np.sin(al)
    matrix[2,0] = a*np.cos(be); matrix[2,1] = b*np.cos(al); matrix[2,2] = c
    return matrix

def rollett_procedure (a,b,c):
    n = np.cross(b,c)
    b_orth = np.cross(c,n)
    a_orth = np.cross(b_orth, c)
    c_orth = c
    return a_orth, b_orth, c_orth
    



In [5]:
# # Direction cosine  LHQipc2B
# X_LHQ = np.array([-1, -8, 1])
# Y_LHQ = np.array([4, -1, -4])
# Z_LHQ = np.array([1, 0, 1])

# # Direction cosine  RHQipc2B
# X_RHQ = np.array([-18, 10, -9])
# Y_RHQ = np.array([4, 9, 2])
# Z_RHQ = np.array([1, 0, -2])

# Direction cosine  L-Alanine
X_Lala = np.array([9, -15, 10])
Y_Lala = np.array([65, 27, -18])
Z_Lala = np.array([0, 2, 3])

# Direction cosine  D-Alanine
X_Rala = np.array([1, -1, 11])
Y_Rala = np.array([11, -11, -2])
Z_Rala = np.array([1, 1, 0])

# crys_ten_LHQ = get_direction_cosine(X_LHQ, Y_LHQ, Z_LHQ)
# crys_ten_RHQ = get_direction_cosine(X_RHQ, Y_RHQ, Z_RHQ)

print('\nDirection cosine matrix for LHQ:\n',crys_ten_LHQ)
# print('\nDirection cosine matrix for RHQ:\n',crys_ten_RHQ)

crys_ten_Lala = get_direction_cosine(X_Lala, Y_Lala, Z_Lala)
crys_ten_Rala = get_direction_cosine(X_Rala, Y_Rala, Z_Rala)

print('\nDirection cosine matrix for L-Alanine:\n',crys_ten_Lala)
print('\nDirection cosine matrix for R-Alanine:\n',crys_ten_Rala)



Direction cosine matrix for LHQ:
 ([-0.12309149097933272, 0.6963106238227914, 0.7071067811865475], [-0.9847319278346618, -0.17407765595569785, 0.0], [0.12309149097933272, -0.6963106238227914, 0.7071067811865475])

Direction cosine matrix for L-Alanine:
 ([0.44666250028691856, 0.8947025264507966, 0.0], [-0.7444375004781977, 0.37164566483340783, 0.5547001962252291], [0.4962916669854651, -0.24776377655560522, 0.8320502943378437])

Direction cosine matrix for R-Alanine:
 ([0.09016696346674323, 0.7013343843696721, 0.7071067811865475], [-0.09016696346674323, -0.7013343843696721, 0.7071067811865475], [0.9918365981341755, -0.12751534261266764, 0.0])


In [3]:
a = 31.113
b = 7.7917
c =  17.9522
alpha = 90
beta = 122.135
gamma = 90
L = rollett_matrix(a, b, c, alpha, beta, gamma)
print(L)

position1 = [0.0757,  0.9292,  0.4647]

position1_orth = np.matmul(L, position1)

print(position1_orth)

[[ 2.63463997e+01  0.00000000e+00  0.00000000e+00]
 [ 2.91848648e-15  7.79170000e+00  0.00000000e+00]
 [-1.65495012e+01  4.77104023e-16  1.79522000e+01]]
[1.99442246 7.24004764 7.0895901 ]


**CAlculation for (++)HQ**

In [3]:
# Orthogonalize the surface normal direction

a_HQ = 20.333
b_HQ = 10.955
c_HQ =  12.550
alpha_HQ = 90
beta_HQ = 109.836
gamma_HQ = 90
rol_mat = rollett_matrix(a_HQ, b_HQ, c_HQ, alpha_HQ, beta_HQ, gamma_HQ)
print(rol_mat)

sn_D = [1, 0, -2] #original surface normal
sn_orth_D = np.matmul(rol_mat, sn_D) # surface normal in orthogonalized system

print('original surface normal:', sn_D, '\n orthogonalized surface normal:', sn_orth_D)

[[ 1.91265973e+01  0.00000000e+00  0.00000000e+00]
 [ 1.66751442e-15  1.09550000e+01  0.00000000e+00]
 [-6.89957709e+00  6.70800284e-16  1.25500000e+01]]
original surface normal: [1, 0, -2] 
 orthogonalized surface normal: [ 1.91265973e+01  1.66751442e-15 -3.19995771e+01]


In [13]:
Y_DHQ = [39, 90, 23]
Z_DHQ = [19, 0, -32 ]

X_DHQ = np.cross(Y_DHQ , Z_DHQ )

print('X_DHQ, Y_DHQ, Z_DHQ, \n', X_DHQ, Y_DHQ, Z_DHQ)

D_HQ_a, D_HQ_b, D_HQ_c = get_direction_cosine(X_DHQ, Y_DHQ, Z_DHQ)

print('L HQ direction cosine:\n', 'a', D_HQ_a, '\n b', D_HQ_b, '\n c', D_HQ_c)

D_HQ_a_orth, D_HQ_b_orth, D_HQ_c_orth = rollett_procedure(D_HQ_a, D_HQ_b, D_HQ_c)

print('L HQ orthogonalized direction cosine:\n', 'a_orth', D_HQ_a_orth, '\n b_orth', D_HQ_b_orth, '\n c_orth',D_HQ_c_orth)


X_DHQ, Y_DHQ, Z_DHQ, 
 [-2880  1685 -1710] [39, 90, 23] [19, 0, -32]
L HQ direction cosine:
 a [-0.768130422548549, 0.3871075002486628, 0.5105387541554361] 
 b [0.44940963958135594, 0.8933250005738372, 0.0] 
 c [-0.456077438388201, 0.22829416681331396, -0.8598547438407345]
L HQ orthogonalized direction cosine:
 a_orth [-0.7677265   0.38622415  0.50975523] 
 b_orth [ 4.48706369e-01  8.93089973e-01 -8.81102191e-04] 
 c_orth [-0.456077438388201, 0.22829416681331396, -0.8598547438407345]


In [6]:
# For DHQ

a =[-0.80098949,  0.39801488 , 0.4472136 ]
b = [ 0.44499416,  0.89553347,  0.        ]
c =  [-0.40049474,  0.19900744, -0.89442719]


a_orth, b_orth, c_orth = rollett_procedure(a, b, c)

print(a_orth, b_orth, c_orth)

alpha_DHQ, beta_DHQ, gamma_DHQ = get_euler_angles(a_orth, b_orth, c_orth)

print(alpha_DHQ, beta_DHQ, gamma_DHQ)



[-0.80098948  0.39801487  0.44721359] [4.44994159e-01 8.95533466e-01 2.58337260e-09] [-0.40049474, 0.19900744, -0.89442719]
-26.422965518932926 153.43494869481555 -3.3097461657298493e-07


**CAlculation for (--)HQ**

In [ ]:
sn_L = [1, 0, 1]
sn_orth_L = np.matmul(rol_mat, sn_L)

print('original surface normal:', sn_L, '\n orthogonalized surface normal:', sn_orth_L)

original surface normal: [1, 0, 1] 
 orthogonalized surface normal: [1.91226203e+01 1.66818889e-15 5.63940793e+00]


In [7]:
Y_LHQ = [30, -17, -96]
Z_LHQ = [19, 0, 6 ]

X_LHQ = np.cross(Y_LHQ , Z_LHQ )

print('X_LHQ, Y_LHQ, Z_LHQ, \n', X_LHQ, Y_LHQ, Z_LHQ)

L_HQ_a, L_HQ_b, L_HQ_c = get_direction_cosine(X_LHQ, Y_LHQ, Z_LHQ)

print('L HQ direction cosine:\n', 'a', L_HQ_a, '\n b', L_HQ_b, '\n c', L_HQ_c)

L_HQ_a_orth, L_HQ_b_orth, L_HQ_c_orth = rollett_procedure(L_HQ_a, L_HQ_b, L_HQ_c)

print('L HQ orthogonalized direction cosine:\n', 'a_orth', L_HQ_a_orth, '\n b_orth', L_HQ_b_orth, '\n c_orth',L_HQ_c_orth)







X_LHQ, Y_LHQ, Z_LHQ, 
 [ -102 -2004   323] [30, -17, -96] [19, 0, 6]
L HQ direction cosine:
 a [-0.05018636820163781, 0.29410351324267087, 0.9535826651341416] 
 b [-0.9860145281968841, -0.16665865750418016, 0.0] 
 c [0.1589234993051864, -0.9411312423765468, 0.3011313679370973]
L HQ orthogonalized direction cosine:
 a_orth [-0.0502697   0.29741421  0.95604403] 
 b_orth [-9.87679368e-01 -1.66797961e-01 -4.42031346e-05] 
 c_orth [0.1589234993051864, -0.9411312423765468, 0.3011313679370973]


In [8]:
# For LHQ

a = [-0.12309149,  0.69631062,  0.70710678]
b = [-0.98473193, -0.17407766,  0.        ]
c =  [ 0.12309149, -0.69631062,  0.70710678]

a_orth, b_orth, c_orth = rollett_procedure(a, b, c)

print(a_orth, b_orth, c_orth)

alpha_LHQ, beta_LHQ, gamma_LHQ = get_euler_angles(a_orth, b_orth, c_orth)

print(alpha_LHQ, beta_LHQ, gamma_LHQ)


[-0.12309149  0.69631062  0.70710677] [-9.84731923e-01 -1.74077657e-01 -2.01417491e-09] [0.12309149, -0.69631062, 0.70710678]
-79.9750121621451 45.00000009614413 1.6320550979899208e-07


In [2]:
# Checking Eichele values in article Single-Crystal 31P and X-ray Diffraction Study

A = [ 392, -278, -114]
B = [  359, -334, -25.5]
dir_x = (A[0]*B[0])/(np.sqrt(np.dot(A, A))*np.sqrt(np.dot(B, B)))
dir_y = (A[1]*B[1])/(np.sqrt(np.dot(A, A))*np.sqrt(np.dot(B, B)))
dir_z = (A[2]*B[2])/(np.sqrt(np.dot(A, A))*np.sqrt(np.dot(B, B)))
print(dir_x, dir_y, dir_z)

0.5802943253441005 0.3828768169578934 0.011987064434762806


In [11]:
angle = np.degrees(np.arccos(X_DHQ[1]/np.sqrt(np.dot(X_DHQ, X_DHQ))))
print(angle)

63.294186653657846


In [6]:
# Checking section 3.1.1 from Trafo Manual
def get_euler_angles(eigenvectors):
    b = np.degrees(np.arccos(eigenvectors[2,2]))
    a = np.degrees(np.arctan(eigenvectors[1,2]/eigenvectors[0,2]))
    g = np.degrees(np.arctan(-eigenvectors[2,1]/eigenvectors[2,0]))

    return a, b, g

efg = np.zeros((3,3))

# efg[0,0] = 541.6395; efg[0,1] = -2.7673; efg[0,2] = 1.7010
# efg[1,0] = -1.2823; efg[1,1] = 541.3822; efg[1,2] = -1.2516
# efg[2,0] = 0.5447; efg[2,1] = 0.9831; efg[2,2] = 645.2708

efg[0,0] = 541.6395; efg[0,1] = -2.0248; efg[0,2] = 1.12285
efg[1,0] = efg[0,1]; efg[1,1] = 541.3822; efg[1,2] = -0.13425
efg[2,0] = efg[0,2]; efg[2,1] = efg[1,2]; efg[2,2] = 645.2708

eigenvalues_efg, eigenvectors_efg = np.linalg.eig(efg)

print(np.real(eigenvalues_efg), '\n', (np.real(eigenvectors_efg)))

get_euler_angles((np.real(eigenvectors_efg)))

[539.47770938 543.53159107 645.28319955] 
 [[-0.68534462 -0.72813787  0.01086248]
 [-0.7281912   0.68537239 -0.0015037 ]
 [ 0.00634994  0.00894051  0.99993987]]


(-7.881421661211974, 0.628321635280185, -54.61599225721839)