In [18]:
import numpy as np

shield_array = np.array([[-62.9830, 166.2263, 80.5663], #shielding tensor
                         [172.4778, 65.9098, -24.7315], 
                         [-8.2278, 25.6984, -51.8337]])

print(shield_array)
eigenvalues, eigenvectors = np.linalg.eig(shield_array) 
print( eigenvalues)



    

[[-62.983  166.2263  80.5663]
 [172.4778  65.9098 -24.7315]
 [ -8.2278  25.6984 -51.8337]]
[ 184.43921018 -164.09917104  -69.24693915]
