In [9]:
import numpy as np

shield_array = np.array( [[90.04079683,  2.49075622,  1.24112347],
                          [-2.10384987, 83.75933965,  6.96559675],
                          [-4.14226695,  2.1483581,  78.10088687]])
shield_array2 = np.array( [[90.04079683, -2.49075622,  1.24112347],
                           [ 2.10384987, 83.75933965, -6.96559675],
                           [-4.14226695, -2.1483581,  78.10088687]])

print(shield_array2)
eigenvalues, eigenvectors = np.linalg.eig(shield_array2) 
print( eigenvalues)



    

[[90.04079683 -2.49075622  1.24112347]
 [ 2.10384987 83.75933965 -6.96559675]
 [-4.14226695 -2.1483581  78.10088687]]
[87.97628784+2.822573j 87.97628784-2.822573j 75.94844768+0.j      ]
