In [4]:
import numpy as np

shield_array = np.array( [[90.04079683,  2.49075622,  1.24112347],
                          [-2.10384987, 83.75933965,  6.96559675],
                          [-4.14226695,  2.1483581,  78.10088687]])
shield_array2 = np.array( [[0.15, -0.27,  -0.17],
                           [ -0.27, -0.09, 0.06],
                           [-0.17, 0.06,  -0.05]])

print(shield_array2)
eigenvalues, eigenvectors = np.linalg.eig(shield_array2) 
print( eigenvalues, eigenvectors)
print(np.average(eigenvalues))



    

[[ 0.15 -0.27 -0.17]
 [-0.27 -0.09  0.06]
 [-0.17  0.06 -0.05]]
[ 0.39491092 -0.27572358 -0.10918734] [[-0.79216008  0.58577097  0.17133238]
 [ 0.48665014  0.77566448 -0.40189085]
 [ 0.36831243  0.23498296  0.89951596]]
0.00333333333333335
