In [15]:
import numpy as np

from sympy import *

In [16]:
def Rabc(alfa1, beta1, gama1): #Euler Rotation Matrix
    U = np.zeros((3, 3))
    #Changing input angles from degrees to radians
    alfa1 = np.radians(alfa1) 
    beta1 = np.radians(beta1)
    gama1 = np.radians(gama1)
    
    U[0, 0] = np.cos(alfa1)*np.cos(beta1)*np.cos(gama1) - np.sin(alfa1)*np.sin(gama1)
    U[0, 1] = np.sin(alfa1)*np.cos(beta1)*np.cos(gama1) + np.cos(alfa1)*np.sin(gama1)
    U[0, 2] = -np.sin(beta1)*np.cos(gama1)
    U[1, 0] = -np.cos(alfa1)*np.cos(beta1)*np.sin(gama1) - np.sin(alfa1)*np.cos(gama1)
    U[1, 1] = -np.sin(alfa1)*np.cos(beta1)*np.sin(gama1) + np.cos(alfa1)*np.cos(gama1)
    U[1, 2] = np.sin(beta1)*np.sin(gama1)
    U[2, 0] = np.cos(alfa1)*np.sin(beta1)
    U[2, 1] = np.sin(alfa1)*np.sin(beta1)
    U[2, 2] = np.cos(beta1)
    return U

In [17]:
a1 = (153.5) #angles for crystal----> Goniometer Frame
b1 = (153.45)
g1 = (180)
R_crystal = Rabc(a1, b1, g1)

a = (308.4) #angles for Quad PAS -----> Goniometer frame
b = (32)
g = (65)

R_total = Rabc(a, b, g)

In [18]:
R_PAS = np.matmul(np.linalg.inv(R_crystal), R_total)
print(R_PAS)

#calculated angles for Quad PAS -----> Crystal Frame
b_PAS = np.degrees(np.arccos(R_PAS[2,2]))
a_PAS = np.degrees(np.arctan(R_PAS[2,1]/R_PAS[2,0]))
g_PAS = np.degrees(np.arctan(-R_PAS[1,2]/R_PAS[0,2]))

print(a_PAS, b_PAS, g_PAS)

[[-0.94373671  0.32620098  0.05435013]
 [ 0.30715866  0.80374522  0.50955586]
 [ 0.12253397  0.49758068 -0.85871933]]
76.16564203231145 149.1730921612314 -83.91174947992909


**Check if Eigen values remain same after rotation**

In [19]:
A = np.zeros((3,3))

A[0,0] = 2; A[0,1] =-3; A[0,2] = 1;
A[1,0] = 1; A[1,1] = -2; A[1,2] = 1;
A[2,0] = 1; A[2,1] = -3; A[2,2] = 2;

print("Original matrix A:")
print(A, '\n')

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:")
print(eigenvalues.real, '\n')

print("Eigenvectors of A:")
print(eigenvectors.real, '\n')


#Rotation matrix
R_T = Rabc(np.radians(20), np.radians(30), np.radians(40))
print("Rotation matrix R:")
print(R_T, '\n')

#Rotated matrix = RAR'

A_rot = np.matmul(np.matmul(R_T, A),np.linalg.inv(R_T))
print("Rotated matrix A_rot:")
print(A_rot, '\n')

# Calculate and print the eigenvalues of the rotated matrix A_rot
eigenvalues_rot, eigenvectors_rot = np.linalg.eig(A_rot)
print("Eigenvalues of A_rot:")
print(eigenvalues_rot, '\n')

# print("Eigenvectors of A_rot:")
# print(eigenvectors_rot)

# A_rot = np.matmul()



Original matrix A:
[[ 2. -3.  1.]
 [ 1. -2.  1.]
 [ 1. -3.  2.]] 

Eigenvalues of A:
[1.33226763e-15 1.00000000e+00 1.00000000e+00] 

Eigenvectors of A:
[[-0.57735027  0.81103583  0.81103583]
 [-0.57735027  0.36250517  0.36250517]
 [-0.57735027  0.27647967  0.27647967]] 

Rotation matrix R:
[[ 9.99791227e-01  1.82757733e-02 -9.13771703e-03]
 [-1.82755189e-02  9.99832983e-01  1.11345822e-04]
 [ 9.13822580e-03  5.56739441e-05  9.99958244e-01]] 

Rotated matrix A_rot:
[[ 1.94418245 -3.04460869  1.01793847]
 [ 0.91867138 -1.96234576  0.99043457]
 [ 0.94439101 -3.04528121  2.01816332]] 

Eigenvalues of A_rot:
[1.18913679e-15 1.00000000e+00 1.00000000e+00] 



**Find Rotation matrix and Euler angles given A and A_rot**

In [20]:
# Find R_T = A_rot*A'
A = np.zeros((3,3))

A[0,0] = -13; A[0,1] = -8; A[0,2] = -4;
A[1,0] = 12; A[1,1] = 7; A[1,2] = 4;
A[2,0] = 24; A[2,1] = 16; A[2,2] = 7;
print("Original matrix A:")
print(A,'\n')

#find eigenvalues and eigenvectors of original matrix
eigenvalues, eigenvectors = np.linalg.eig(A) 

print('Eigenvalues of A:\n', eigenvalues, '\n')
print('Eigenvectors of A:\n', eigenvectors, '\n')

#Find rotation matrix with Euler angles (20, 30, 40) degrees
R_T_original = Rabc(np.radians(20), np.radians(30), np.radians(40))
print("Original Rotation matrix:")
print(R_T_original,'\n')

#finding Rotated matrix
#A_rot = RAR'

A_rot = np.matmul(np.matmul(R_T_original, A),np.linalg.inv(R_T_original))


# Calculate the eigenvalues of the rotated matrix A_rot
eigenvalues_rot, eigenvectors_rot = np.linalg.eig(A_rot)
print('Eigenvalues of A_rot:\n', eigenvalues_rot, '\n')
print('Eigenvectors of A_rot:\n', eigenvectors_rot, '\n')

# Calculate Rotation matrix given original and rotated matrix eigenvectors
R_T = np.matmul(eigenvectors_rot, np.linalg.inv(eigenvectors))
print("Calculated Rotation matrix:")
print(R_T,'\n')

b = np.degrees(np.arccos(A_rot[2,2]))
a = np.degrees(np.arctan(A_rot[2,1]/A_rot[2,0]))
g = np.degrees(np.arctan(-A_rot[1,2]/A_rot[0,2]))
print("Calculated Euler angles (degrees):")
print(a, b, g,'\n')


Original matrix A:
[[-13.  -8.  -4.]
 [ 12.   7.   4.]
 [ 24.  16.   7.]] 

Eigenvalues of A:
 [-1.  3. -1.] 

Eigenvectors of A:
 [[-0.51214752 -0.40824829  0.07785028]
 [ 0.38411064  0.40824829 -0.53682312]
 [ 0.76822128  0.81649658  0.84009539]] 

Original Rotation matrix:
[[ 9.99791227e-01  1.82757733e-02 -9.13771703e-03]
 [-1.82755189e-02  9.99832983e-01  1.11345822e-04]
 [ 9.13822580e-03  5.56739441e-05  9.99958244e-01]] 

Eigenvalues of A_rot:
 [-1.  3. -1.] 

Eigenvectors of A_rot:
 [[-0.51123571 -0.40816292 -0.11282054]
 [ 0.39138279  0.41573197 -0.32115976]
 [ 0.76515198  0.81275455  0.94028077]] 

Calculated Rotation matrix:
[[ 0.9935059   0.19597761 -0.1011313 ]
 [-0.0018037   0.78172451  0.11740149]
 [-0.00352623 -0.11055962  1.04893366]] 

Calculated Euler angles (degrees):
32.72395740893625 nan 45.526356333883065 



/tmp/ipykernel_3913871/2437861666.py:37: RuntimeWarning: invalid value encountered in arccos
  b = np.degrees(np.arccos(A_rot[2,2]))


In [21]:
A = np.zeros((3,3))

A[0,0] = -13; A[0,1] = -8; A[0,2] = -4;
A[1,0] = 12; A[1,1] = 7; A[1,2] = 4;
A[2,0] = 24; A[2,1] = 16; A[2,2] = 7;

B = np.zeros((2,2))
B[0,0] = 1; B[0,1] = 2;
B[1,0] = 1; B[1,1] = -1;
print(B)

eigenvalues, eigenvectors = np.linalg.eig(A) 

x_ev = eigenvectors[:,0]
y_ev = eigenvectors[:,1]
z_ev = eigenvectors[:,2]

dc = np.stack((x_ev, y_ev, z_ev), axis = 1)

print(eigenvalues)
print(eigenvectors)
print(x_ev, '\n' , y_ev, '\n', z_ev)
print(dc)








[[ 1.  2.]
 [ 1. -1.]]
[-1.  3. -1.]
[[-0.51214752 -0.40824829  0.07785028]
 [ 0.38411064  0.40824829 -0.53682312]
 [ 0.76822128  0.81649658  0.84009539]]
[-0.51214752  0.38411064  0.76822128] 
 [-0.40824829  0.40824829  0.81649658] 
 [ 0.07785028 -0.53682312  0.84009539]
[[-0.51214752 -0.40824829  0.07785028]
 [ 0.38411064  0.40824829 -0.53682312]
 [ 0.76822128  0.81649658  0.84009539]]


In [22]:
A = np.zeros((3,3))

A[0,0] = 2; A[0,1] =-3; A[0,2] = 1;
A[1,0] = 1; A[1,1] = -2; A[1,2] = 1;
A[2,0] = 1; A[2,1] = -3; A[2,2] = 2;

A1 = np.zeros((3,3))

A1[0,0] = -13; A1[0,1] = -8; A1[0,2] = -4;
A1[1,0] = 12; A1[1,1] = 7; A1[1,2] = 4;
A1[2,0] = 24; A1[2,1] = 16; A1[2,2] = 7;

B = np.matmul(A1, A)

print(B)

print(np.matmul(np.linalg.inv(A1), B))


[[ -38.   67.  -29.]
 [  35.  -62.   27.]
 [  71. -125.   54.]]
[[ 2. -3.  1.]
 [ 1. -2.  1.]
 [ 1. -3.  2.]]


**Calculation for D-HQ**

In [23]:
# site 1
a = (153.5) #angles for crystal----> Goniometer Frame
b = (153.4)
g = (179.9)
R_crystal = Rabc(a, b, g)

a1 = (319) #angles for Quad PAS -----> Goniometer frame
b1 = (28.8)
g1 = (62)

R_total = Rabc(a1, b1, g1)

R_PAS = np.matmul(np.linalg.inv(R_crystal), R_total)

#calculated angles for Quad PAS -----> Crystal Frame
l_PAS = np.degrees(np.arccos(R_PAS[2,2]))
z_PAS = np.degrees(np.arctan(R_PAS[2,1]/R_PAS[2,0]))
n_PAS = np.degrees(np.arctan(-R_PAS[1,2]/R_PAS[0,2]))

print(f'Euler angles for Quadrupolar tensor PAS ----> Crystal frame for D-HQ:\n zeta:{np.round(z_PAS, 1)} lambda:{np.round(l_PAS, 1)} nu:{np.round(n_PAS, 1)}' )

Euler angles for Quadrupolar tensor PAS ----> Crystal frame for D-HQ:
 zeta:81.0 lambda:152.2 nu:-87.6


In [24]:
# site 2
a = (153.5) #angles for crystal----> Goniometer Frame
b = (153.4)
g = (179.9)
R_crystal = Rabc(a, b, g)

a1 = (84.8) #angles for Quad PAS -----> Goniometer frame
b1 = (36.9)
g1 = (334.8)

R_total = Rabc(a1, b1, g1)

R_PAS = np.matmul(np.linalg.inv(R_crystal), R_total)

#calculated angles for Quad PAS -----> Crystal Frame
l_PAS = np.degrees(np.arccos(R_PAS[2,2]))
z_PAS = np.degrees(np.arctan(R_PAS[2,1]/R_PAS[2,0]))
n_PAS = np.degrees(np.arctan(-R_PAS[1,2]/R_PAS[0,2]))

print(f'Euler angles for Quadrupolar tensor PAS ----> Crystal frame D-HQ:\n zeta:{np.round(z_PAS, 1)} lambda:{np.round(l_PAS, 1)} nu:{np.round(n_PAS, 1)}' )

Euler angles for Quadrupolar tensor PAS ----> Crystal frame D-HQ:
 zeta:-53.4 lambda:163.4 nu:89.8


**Calculation for L-HQ**

In [25]:
# site 1
a = (280) #angles for crystal----> Goniometer Frame
b = (45)
g = (180)
R_crystal = Rabc(a, b, g)

a1 = (250.3) #angles for Quad PAS -----> Goniometer frame
b1 = (60)
g1 = (127.1)

R_total = Rabc(a1, b1, g1)

R_PAS = np.matmul(np.linalg.inv(R_crystal), R_total)

#calculated angles for Quad PAS -----> Crystal Frame
l_PAS = np.degrees(np.arccos(R_PAS[2,2]))
z_PAS = np.degrees(np.arctan(R_PAS[2,1]/R_PAS[2,0]))
n_PAS = np.degrees(np.arctan(-R_PAS[1,2]/R_PAS[0,2]))

print(f'Euler angles for Quadrupolar tensor PAS ----> Crystal frame L-HQ:\n zeta:{np.round(z_PAS, 1)} lambda:{np.round(l_PAS, 1)} nu:{np.round(n_PAS, 1)}' )

Euler angles for Quadrupolar tensor PAS ----> Crystal frame L-HQ:
 zeta:-55.0 lambda:43.7 nu:-8.7


In [26]:
# site 2
a = (280) #angles for crystal----> Goniometer Frame
b = (45)
g = (180)
R_crystal = Rabc(a, b, g)

a1 = (57.8) #angles for Quad PAS -----> Goniometer frame
b1 = (71.6)
g1 = (309.2)

R_total = Rabc(a1, b1, g1)

R_PAS = np.matmul(np.linalg.inv(R_crystal), R_total)

#calculated angles for Quad PAS -----> Crystal Frame
l_PAS = np.degrees(np.arccos(R_PAS[2,2]))
z_PAS = np.degrees(np.arctan(R_PAS[2,1]/R_PAS[2,0]))
n_PAS = np.degrees(np.arctan(-R_PAS[1,2]/R_PAS[0,2]))

print(f'Euler angles for Quadrupolar tensor PAS ----> Crystal frame L-HQ:\n zeta:{np.round(z_PAS, 1)} lambda:{np.round(l_PAS, 1)} nu:{np.round(n_PAS, 1)}' )

Euler angles for Quadrupolar tensor PAS ----> Crystal frame L-HQ:
 zeta:23.8 lambda:101.6 nu:31.4


**L-Alanine**

In [32]:
a = (333.5) # angles for crystal----> Goniometer Frame (from XRD)
b = (33.7)
g = (90.0)


R_crystal = Rabc(a, b, g)


angle_sets = {                              # angles for PAS(Q) -----> Goniometer frame (from ASICS)
    "Site1": [[48.0, 46.9, 336.1], 
               [309.9, 24.4, 102.4], 
               [128.7, 49.6, 203.3],
               [118.3, 6.9, 57.9]],
    
    "Site2": [[263.2, 9.1, 149.8], 
               [223.1, 1.0, 2.5], 
               [170.5, 38.5, 323.3],
               [145.3, 56.3, 37.5]]
}

for label, angles in angle_sets.items():
    print(f"\n===== Results for {label} =====\n")
    
    for i, ang in enumerate(angles):
        R_Lala_total = Rabc(ang[0], ang[1], ang[2])
        R_PAS_Lala = np.matmul(np.linalg.inv(R_crystal), R_Lala_total)

        # Use arctan2 to handle quadrant correctly
        z_PAS = np.degrees(np.arctan(R_PAS_Lala[2, 1]/ R_PAS_Lala[2, 0]))
        n_PAS = np.degrees(np.arctan(-R_PAS_Lala[1, 2] / R_PAS_Lala[0, 2]))
        l_PAS = np.degrees(np.arccos(R_PAS_Lala[2, 2]))

        print(f"Nucleus: {i+1},\n{R_PAS_Lala}\n")
        print(f"Euler angles for Quadrupolar tensor PAS → Tenon frame (L-alanine):")
        print(f" alpha_QG: {np.round(ang[0], 0)}, beta_QG: {np.round(ang[1], 0)}, gamma_QG: {np.round(ang[2], 0)}\n")
        print(f"Euler angles for Quadrupolar tensor PAS → Crystal frame (L-alanine):")
        print(f" zeta: {np.round(z_PAS, 0)}, lambda: {np.round(l_PAS, 0)}, nu: {np.round(n_PAS, 0)}\n")


===== Results for Site1 =====

Nucleus: 1,
[[ 0.93139916 -0.25303195  0.26166856]
 [ 0.33911645  0.34197106 -0.87638795]
 [ 0.13227108  0.90500311  0.40431885]]

Euler angles for Quadrupolar tensor PAS → Tenon frame (L-alanine):
 alpha_QG: 48.0, beta_QG: 47.0, gamma_QG: 336.0

Euler angles for Quadrupolar tensor PAS → Crystal frame (L-alanine):
 zeta: 82.0, lambda: 66.0, nu: 73.0

Nucleus: 2,
[[ 0.95736958 -0.21637174  0.19138119]
 [ 0.21974062  0.9755513   0.00370334]
 [-0.18750347  0.03850876  0.9815088 ]]

Euler angles for Quadrupolar tensor PAS → Tenon frame (L-alanine):
 alpha_QG: 310.0, beta_QG: 24.0, gamma_QG: 102.0

Euler angles for Quadrupolar tensor PAS → Crystal frame (L-alanine):
 zeta: -12.0, lambda: 11.0, nu: -1.0

Nucleus: 3,
[[-0.34695875 -0.37834167  0.8581825 ]
 [ 0.93380259 -0.05412072  0.35367169]
 [-0.08736328  0.92408253  0.37207409]]

Euler angles for Quadrupolar tensor PAS → Tenon frame (L-alanine):
 alpha_QG: 129.0, beta_QG: 50.0, gamma_QG: 203.0

Euler angles

**D-Alanine**

In [ ]:
a = (352.7) # angles for crystal----> Goniometer Frame (from XRD)
b = (90.0)
g = (135.0)


R_crystal = Rabc(a, b, g)


angle_sets = {                              # angles for PAS(Q) -----> Goniometer frame (from ASICS)
    "Site1": [[304.1, 21.0 , 80.0], 
               [307.6, 19.0, 80.0], 
               [248.0, 35.0, 80.0],
               [-89.9, 39.0 , 70.0 ]],
    
    "Site2": [[318.1, 39.1, 348.1], 
               [210.4, 19.2, 19.2], 
               [37.1, 35.9, 180.2],
               [341.5, 66.0, 40.3]]
}

for label, angles in angle_sets.items():
    print(f"\n===== Results for {label} =====\n")
    
    for i, ang in enumerate(angles):
        R_Lala_total = Rabc(ang[0], ang[1], ang[2])
        R_PAS_Lala = np.matmul(np.linalg.inv(R_crystal), R_Lala_total)

        # Use arctan2 to handle quadrant correctly
        z_PAS = np.degrees(np.arctan(R_PAS_Lala[2, 1]/ R_PAS_Lala[2, 0]))
        n_PAS = np.degrees(np.arctan(-R_PAS_Lala[1, 2] / R_PAS_Lala[0, 2]))
        l_PAS = np.degrees(np.arccos(R_PAS_Lala[2, 2]))

        print(f"Nucleus: {i+1},\n{R_PAS_Lala}\n")
        print(f"Euler angles for Quadrupolar tensor PAS → Tenon frame (D-alanine):")
        print(f" alpha_QG: {np.round(ang[0], 0)}, beta_QG: {np.round(ang[1], 0)}, gamma_QG: {np.round(ang[2], 0)}\n")
        print(f"Euler angles for Quadrupolar tensor PAS → Crystal frame (D-alanine):")
        print(f" zeta: {np.round(z_PAS, 0)}, lambda: {np.round(l_PAS, 0)}, nu: {np.round(n_PAS, 0)}\n")


===== Results for Site1 =====

Nucleus: 1,
[[ 0.31411498 -0.33394911  0.88871242]
 [ 0.87084718 -0.27145228 -0.40980342]
 [ 0.3780965   0.90265811  0.20555141]]

Euler angles for Quadrupolar tensor PAS → Tenon frame (D-alanine):
 alpha_QG: 304.0, beta_QG: 21.0, gamma_QG: 80.0

Euler angles for Quadrupolar tensor PAS → Crystal frame (D-alanine):
 zeta: 67.0, lambda: 78.0, nu: 25.0

Nucleus: 2,
[[ 0.31482393 -0.28935815  0.90396778]
 [ 0.89425588 -0.22876916 -0.3846701 ]
 [ 0.31810738  0.92948186  0.18673822]]

Euler angles for Quadrupolar tensor PAS → Tenon frame (D-alanine):
 alpha_QG: 308.0, beta_QG: 19.0, gamma_QG: 80.0

Euler angles for Quadrupolar tensor PAS → Crystal frame (D-alanine):
 zeta: 71.0, lambda: 79.0, nu: 23.0

Nucleus: 3,
[[-0.17748915 -0.6338552   0.75281152]
 [ 0.30547465 -0.76265641 -0.57012318]
 [ 0.93551208  0.12877416  0.32898993]]

Euler angles for Quadrupolar tensor PAS → Tenon frame (D-alanine):
 alpha_QG: 248.0, beta_QG: 35.0, gamma_QG: 80.0

Euler angles fo