In [1]:
import numpy as np
from functions import Rabc
from sympy import *

In [2]:
a1 = np.radians(153.5) #angles for crystal----> Goniometer Frame
b1 = np.radians(153.45)
g1 = np.radians(180)
R_crystal = Rabc(a1, b1, g1)

a = np.radians(308.4) #angles for Quad PAS -----> Goniometer frame
b = np.radians(32)
g = np.radians(65)

R_total = Rabc(a, b, g)

In [3]:
R_PAS = np.matmul(np.linalg.inv(R_crystal), R_total)
print(R_PAS)

#calculated angles for Quad PAS -----> Crystal Frame
b_PAS = np.degrees(np.arccos(R_PAS[2,2]))
a_PAS = np.degrees(np.arctan(R_PAS[2,1]/R_PAS[2,0]))
g_PAS = np.degrees(np.arctan(-R_PAS[1,2]/R_PAS[0,2]))

print(a_PAS, b_PAS, g_PAS)

[[-0.94373671  0.32620098  0.05435013]
 [ 0.30715866  0.80374522  0.50955586]
 [ 0.12253397  0.49758068 -0.85871933]]
76.16564203231145 149.1730921612314 -83.91174947992909


**Check if Eigen values remain same after rotation**

In [7]:
A = np.zeros((3,3))

A[0,0] = 2; A[0,1] =-3; A[0,2] = 1;
A[1,0] = 1; A[1,1] = -2; A[1,2] = 1;
A[2,0] = 1; A[2,1] = -3; A[2,2] = 2;

print("Original matrix A:")
print(A, '\n')

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:")
print(eigenvalues.real, '\n')

print("Eigenvectors of A:")
print(eigenvectors.real, '\n')


#Rotation matrix
R_T = Rabc(np.radians(20), np.radians(30), np.radians(40))
print("Rotation matrix R:")
print(R_T, '\n')

#Rotated matrix = RAR'

A_rot = np.matmul(np.matmul(R_T, A),np.linalg.inv(R_T))
print("Rotated matrix A_rot:")
print(A_rot, '\n')

# Calculate and print the eigenvalues of the rotated matrix A_rot
eigenvalues_rot, eigenvectors_rot = np.linalg.eig(A_rot)
print("Eigenvalues of A_rot:")
print(eigenvalues_rot, '\n')

# print("Eigenvectors of A_rot:")
# print(eigenvectors_rot)

# A_rot = np.matmul()



Original matrix A:
[[ 2. -3.  1.]
 [ 1. -2.  1.]
 [ 1. -3.  2.]] 

Eigenvalues of A:
[1.33226763e-15 1.00000000e+00 1.00000000e+00] 

Eigenvectors of A:
[[-0.57735027  0.81103583  0.81103583]
 [-0.57735027  0.36250517  0.36250517]
 [-0.57735027  0.27647967  0.27647967]] 

Rotation matrix R:
[[ 0.40355888  0.83092371 -0.38302222]
 [-0.7851017   0.52945382  0.3213938 ]
 [ 0.46984631  0.17101007  0.8660254 ]] 

Rotated matrix A_rot:
[[-1.10500966 -1.74725572  0.70061692]
 [-0.16253935  0.86508479  0.05409848]
 [-3.72536508 -3.09222593  2.23992487]] 

Eigenvalues of A_rot:
[-8.8817842e-16  1.0000000e+00  1.0000000e+00] 

[[  4.9559063   -3.61043977  -2.61081458]
 [ -1.27372034  -3.7774777    3.11144765]
 [  2.12835554 -17.5428264    2.30940108]]


**Find Rotation matrix and Euler angles given A and A_rot**

In [5]:
# Find R_T = A_rot*A'
A = np.zeros((3,3))

A[0,0] = -13; A[0,1] = -8; A[0,2] = -4;
A[1,0] = 12; A[1,1] = 7; A[1,2] = 4;
A[2,0] = 24; A[2,1] = 16; A[2,2] = 7;
print("Original matrix A:")
print(A,'\n')

#find eigenvalues and eigenvectors of original matrix
eigenvalues, eigenvectors = np.linalg.eig(A) 

print('Eigenvalues of A:\n', eigenvalues, '\n')
print('Eigenvectors of A:\n', eigenvectors, '\n')

#Find rotation matrix with Euler angles (20, 30, 40) degrees
R_T_original = Rabc(np.radians(20), np.radians(30), np.radians(40))
print("Original Rotation matrix:")
print(R_T_original,'\n')

#finding Rotated matrix
#A_rot = RAR'

A_rot = np.matmul(np.matmul(R_T_original, A),np.linalg.inv(R_T_original))


# Calculate the eigenvalues of the rotated matrix A_rot
eigenvalues_rot, eigenvectors_rot = np.linalg.eig(A_rot)
print('Eigenvalues of A_rot:\n', eigenvalues_rot, '\n')
print('Eigenvectors of A_rot:\n', eigenvectors_rot, '\n')

# Calculate Rotation matrix given original and rotated matrix eigenvectors
R_T = np.matmul(eigenvectors_rot, np.linalg.inv(eigenvectors))
print("Calculated Rotation matrix:")
print(R_T,'\n')

b = np.degrees(np.arccos(A_rot[2,2]))
a = np.degrees(np.arctan(A_rot[2,1]/A_rot[2,0]))
g = np.degrees(np.arctan(-A_rot[1,2]/A_rot[0,2]))
print("Calculated Euler angles (degrees):")
print(a, b, g,'\n')


Original matrix A:
[[-13.  -8.  -4.]
 [ 12.   7.   4.]
 [ 24.  16.   7.]] 

Eigenvalues of A:
 [-1.  3. -1.] 

Eigenvectors of A:
 [[-0.51214752 -0.40824829  0.07785028]
 [ 0.38411064  0.40824829 -0.53682312]
 [ 0.76822128  0.81649658  0.84009539]] 

Original Rotation matrix:
[[ 0.40355888  0.83092371 -0.38302222]
 [-0.7851017   0.52945382  0.3213938 ]
 [ 0.46984631  0.17101007  0.8660254 ]] 

Eigenvalues of A_rot:
 [ 3. -1. -1.] 

Eigenvectors of A_rot:
 [[ 0.13826537 -0.58767824  0.25522609]
 [-0.79908199  0.39507516 -0.8012364 ]
 [-0.5851074   0.70608066 -0.54118377]] 

Calculated Rotation matrix:
[[-5.39842256 -3.70766183 -1.56513628]
 [ 9.1442275   6.02027204  2.04584401]
 [ 9.75844688  6.40251831  2.54273295]] 

Calculated Euler angles (degrees):
-21.38760033244556 nan 80.1832944519319 



/tmp/ipykernel_2878378/2437861666.py:37: RuntimeWarning: invalid value encountered in arccos
  b = np.degrees(np.arccos(A_rot[2,2]))


In [1]:
A = np.zeros((2,2))
A[0,0] = 0; A[0,1] = 1;
A[1,0] = -2; A[1,1] = -3;
print(A)

B = np.zeros((2,2))
B[0,0] = 1; B[0,1] = 2;
B[1,0] = 1; B[1,1] = -1;
print(B)

eigenvalues, eigenvectors = np.linalg.eig(A) 
print(eigenvalues)
print(eigenvectors)



<IPython.core.display.Javascript object>

[[ 0.  1.]
 [-2. -3.]]


<IPython.core.display.Javascript object>

[[ 1.  2.]
 [ 1. -1.]]


<IPython.core.display.Javascript object>

[-1. -2.]
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]
