In [4]:
import numpy as np
from functions import Rabc

In [3]:
a1 = np.radians(153.5) #angles for crystal----> Goniometer Frame
b1 = np.radians(153.45)
g1 = np.radians(180)
R_crystal = Rabc(a1, b1, g1)

a = np.radians(308.4) #angles for Quad PAS -----> Goniometer frame
b = np.radians(32)
g = np.radians(65)

R_total = Rabc(a, b, g)

In [4]:
R_PAS = np.matmul(np.linalg.inv(R_crystal), R_total)
print(R_PAS)

#calculated angles for Quad PAS -----> Crystal Frame
b_PAS = np.degrees(np.arccos(R_PAS[2,2]))
a_PAS = np.degrees(np.arctan(R_PAS[2,1]/R_PAS[2,0]))
g_PAS = np.degrees(np.arctan(-R_PAS[1,2]/R_PAS[0,2]))

print(a_PAS, b_PAS, g_PAS)

[[-0.94373671  0.32620098  0.05435013]
 [ 0.30715866  0.80374522  0.50955586]
 [ 0.12253397  0.49758068 -0.85871933]]
76.16564203231145 149.1730921612314 -83.91174947992909


**Check if Eigen values remain same after rotation**

In [32]:


A = np.zeros((3,3))

A[0,0] = -2; A[0,1] = -4; A[0,2] = 2;
A[1,0] = -2; A[1,1] = 1; A[1,2] = 2;
A[2,0] = 4; A[2,1] = 2; A[2,2] = 5;

print("Original matrix A:")
print(A)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:")
print(eigenvalues)
print("Eigenvectors of A:")
print(eigenvectors)


#Rotation matrix
R_T = Rabc(np.radians(20), np.radians(30), np.radians(40))
print("Rotation matrix R:")
print(R_T)

#Rotated matrix = RAR'

A_rot = np.matmul(np.matmul(R_T, A),np.linalg.inv(R_T))
print("Rotated matrix A_rot:")
print(A_rot)

# Calculate and print the eigenvalues of the rotated matrix A_rot
eigenvalues_rot, eigenvectors_rot = np.linalg.eig(A_rot)
print("Eigenvalues of A_rot:")
print(eigenvalues_rot)

print("Eigenvectors of A_rot:")
print(eigenvectors_rot)

# A_rot = np.matmul()

Original matrix A:
[[-2. -4.  2.]
 [-2.  1.  2.]
 [ 4.  2.  5.]]
Eigenvalues of A:
[-5.  3.  6.]
Eigenvectors of A:
[[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]
Rotation matrix R:
[[ 0.40355888  0.83092371 -0.38302222]
 [-0.7851017   0.52945382  0.3213938 ]
 [ 0.46984631  0.17101007  0.8660254 ]]
Rotated matrix A_rot:
[[-3.11419617  2.49892701 -1.66518432]
 [ 3.88895767  1.22476423  2.53064036]
 [-1.24906429  0.10274851  5.88943194]]
Eigenvalues of A_rot:
[-5.  3.  6.]
Eigenvectors of A_rot:
[[ 0.8250958  -0.34814282 -0.0431877 ]
 [-0.55609271 -0.93005807  0.44013643]
 [ 0.09988908 -0.1174247   0.89689171]]


**Find Rotation matrix and Euler angles given A and A_rot**

In [36]:
# Find R_T = A_rot*A'
A = np.zeros((3,3))

A[0,0] = -2; A[0,1] = -4; A[0,2] = 2;
A[1,0] = -2; A[1,1] = 1; A[1,2] = 2;
A[2,0] = 4; A[2,1] = 2; A[2,2] = 5;
print("Original matrix A:")
print(A)

R_T_original = Rabc(np.radians(20), np.radians(30), np.radians(40))
print("Original Rotation matrix:")
print(R_T_original)

R_T = np.matmul(eigenvectors_rot, np.linalg.inv(eigenvectors))
print("Calculated Rotation matrix:")
print(R_T)

b = np.degrees(np.arccos(R_T[2,2]))
a = np.degrees(np.arctan(R_T[2,1]/R_T[2,0]))
g = np.degrees(np.arctan(-R_T[1,2]/R_T[0,2]))
print("Calculated Euler angles (degrees):")
print(a, b, g)


Original matrix A:
[[-2. -4.  2.]
 [-2.  1.  2.]
 [ 4.  2.  5.]]
Original Rotation matrix:
[[ 0.40355888  0.83092371 -0.38302222]
 [-0.7851017   0.52945382  0.3213938 ]
 [ 0.46984631  0.17101007  0.8660254 ]]
Calculated Rotation matrix:
[[ 0.40355888  0.83092371 -0.38302222]
 [-0.7851017   0.52945382  0.3213938 ]
 [ 0.46984631  0.17101007  0.8660254 ]]
Calculated Euler angles (degrees):
20.00000000000007 30.000000000000043 40.00000000000005
