In [1]:
import numpy as np
from functions import Rabc

In [4]:
a1 = np.radians(80) #angles for crystal----> Goniometer Frame
b1 = np.radians(45)
g1 = np.radians(14.5)
R_crystal = Rabc(a1, b1, g1)

a = np.radians(283.5) #angles for Quad PAS -----> Goniometer frame
b = np.radians(68)
g = np.radians(30)

R_total = Rabc(a, b, g)

In [5]:
R_PAS = np.matmul(np.linalg.inv(R_crystal), R_total)
print(R_PAS)

#calculated angles for Quad PAS -----> Crystal Frame
b_PAS = np.degrees(np.arccos(R_PAS[2,2]))
a_PAS = np.degrees(np.arctan(R_PAS[2,1]/R_PAS[2,0]))
g_PAS = np.degrees(np.arctan(-R_PAS[1,2]/R_PAS[0,2]))

print(a_PAS, b_PAS, g_PAS)

[[-0.83092377 -0.46354249 -0.30772398]
 [ 0.54901268 -0.77283819 -0.31828638]
 [-0.09028158 -0.43341608  0.89666032]]
78.23341342279502 26.277503966844694 -45.96663513365225


In [10]:
print(R_PAS[1,2])

-0.3182863769542534
