**This code is to check the Eigenvalues for EFG tensor provided by Gaussian**

*Current Concern: Tensor not traceless*

In [9]:
# Sort eigenvalues of tensors as per the convention defined in article
def sort_eigenvalues(Tensor):
    #Calculate Quadrupolar Tensor in PAS
    eigenvalues, eigenvectors = np.linalg.eig(Tensor)
    print(' Unsorted Eigenvalues:\n', eigenvalues, '\n')
    print(' Unsorted Eigenvectors:\n', eigenvectors, '\n')

    avg_tensor = np.mean(eigenvalues) # Tr(A)Quad/3
    eigenvalue_diff = eigenvalues - avg_tensor

    # Get the indices of the sorted eigenvalues based on the absolute values
    sorted_indices = np.argsort(np.abs(eigenvalue_diff))

    # Sort both eigenvalues and eigenvectors using the sorted indices
    sorted_eigenvalues = eigenvalues[sorted_indices]
    sorted_eigenvectors = eigenvectors[:, sorted_indices] # The normalized (unit “length”) eigenvectors, 
    #                                                       such that the column eigenvectors[:,i] is the eigenvector corresponding to the eigenvalue eigenvalues[i]
    # eigenvectors need to be arranged so that first column for direction cosine matrix is eigenvector for x, second column is for y and third column is for z
    y_dc = sorted_eigenvectors[:,0]
    x_dc = sorted_eigenvectors[:,1]
    z_dc = sorted_eigenvectors[:,2]

    dc = np.stack((x_dc, y_dc, z_dc), axis = 1)


    print('Sorted Eigenvalues: \n', sorted_eigenvalues, '\n')
    print('Sorted Eigenvectors: \n', sorted_eigenvectors, '\n')
    print(f'isotropic tensor element: {avg_tensor:.1f}')
    print(f'traceless eigenvalue elements: {eigenvalue_diff}')
    return sorted_eigenvalues, dc,  avg_tensor, eigenvalues, eigenvectors

In [11]:
# efg used from Trafo manual

efg_trafo = np.zeros((3, 3 ))                             # efg Tensor from magres (in a.u.)
efg_trafo[0,0]= -509.762431; efg_trafo[0,1]= -0.004232; efg_trafo[0,2]= -0.004145;
efg_trafo[1,0]=efg_trafo[0,1]; efg_trafo[1,1]= -509.762712; efg_trafo[1,2]= 0.004080;
efg_trafo[2,0]=efg_trafo[0,2]; efg_trafo[2,1]=efg_trafo[1,2]; efg_trafo[2,2]= -509.915770;



sort_eigenvalues(efg_trafo)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

 Unsorted Eigenvalues:
 [-509.75812261 -509.76680581 -509.91598458] 

 Unsorted Eigenvectors:
 [[ 7.18104513e-01 -6.95439573e-01  2.62623294e-02]
 [-6.94958085e-01 -7.18584506e-01 -2.58760179e-02]
 [-3.68669098e-02 -3.30467048e-04  9.99320130e-01]] 



<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Sorted Eigenvalues: 
 [-509.76680581 -509.75812261 -509.91598458] 

Sorted Eigenvectors: 
 [[-6.95439573e-01  7.18104513e-01  2.62623294e-02]
 [-7.18584506e-01 -6.94958085e-01 -2.58760179e-02]
 [-3.30467048e-04 -3.68669098e-02  9.99320130e-01]] 

isotropic tensor element: -509.8
traceless eigenvalue elements: [ 0.05551506  0.04683185 -0.10234691]


(array([-509.76680581, -509.75812261, -509.91598458]),
 array([[ 7.18104513e-01, -6.95439573e-01,  2.62623294e-02],
        [-6.94958085e-01, -7.18584506e-01, -2.58760179e-02],
        [-3.68669098e-02, -3.30467048e-04,  9.99320130e-01]]),
 -509.8136376666664,
 array([-509.75812261, -509.76680581, -509.91598458]),
 array([[ 7.18104513e-01, -6.95439573e-01,  2.62623294e-02],
        [-6.94958085e-01, -7.18584506e-01, -2.58760179e-02],
        [-3.68669098e-02, -3.30467048e-04,  9.99320130e-01]]))