In [2]:
import numpy as np

#define CS Tensor function
def cs_tensor(delta_iso, delta, eta_cs):
    CS_PAS = np.zeros((3,3))
    CS_PAS[0,0] = delta_iso - (delta/2)*(1 + eta_cs)
    CS_PAS[1,1] = delta_iso - (delta/2)*(1 - eta_cs)
    CS_PAS[2,2] = delta_iso + delta

    return CS_PAS

#define Quadrupolar Tensor fucntion
def quad_tensor(CQ, eta_Q):
    Q_PAS = np.zeros((3,3))
    Q_PAS[0,0] = (-CQ/2)*(1-eta_Q)
    Q_PAS[1,1] = (-CQ/2)*(1+eta_Q)
    Q_PAS[2,2] = CQ

    return Q_PAS



In [3]:
#Input values for ++8HQ (cluster1 , cluster2)
RHQ_delta_iso = [-8,-8]
RHQ_delta = [-9.08, -9.25]
RHQ_eta_cs = [0.88, 0.3]
RHQ_CQ = [2.18, 2.182]
RHQ_eta_Q = [0.935, 0.915]

for i, (delta_iso, delta, eta_cs, CQ, eta_Q) in enumerate(zip(RHQ_delta_iso, RHQ_delta, RHQ_eta_cs, RHQ_CQ, RHQ_eta_Q)):
    RHQ_CS_tensor  = cs_tensor(delta_iso, delta, eta_cs)
    RHQ_Q_tensor = quad_tensor(CQ, eta_Q)
    print(f'++8HQ CS Tensor Cluster{i+1}:\n', RHQ_CS_tensor)
    print(f'++8HQ Quadrupolar Tensor Cluster{i+1}:\n', RHQ_Q_tensor)
    print('==============================')



++8HQ CS Tensor Cluster1:
 [[  0.5352   0.       0.    ]
 [  0.      -7.4552   0.    ]
 [  0.       0.     -17.08  ]]
++8HQ Quadrupolar Tensor Cluster1:
 [[-0.07085  0.       0.     ]
 [ 0.      -2.10915  0.     ]
 [ 0.       0.       2.18   ]]
++8HQ CS Tensor Cluster2:
 [[ -1.9875   0.       0.    ]
 [  0.      -4.7625   0.    ]
 [  0.       0.     -17.25  ]]
++8HQ Quadrupolar Tensor Cluster2:
 [[-0.092735  0.        0.      ]
 [ 0.       -2.089265  0.      ]
 [ 0.        0.        2.182   ]]


In [4]:
#Input values for --8HQ (cluster1 , cluster2)
LHQ_delta_iso = [-8.3,-9]
LHQ_delta = [17.56, -32.43]
LHQ_eta_cs = [0.38, 0.82]
LHQ_CQ = [2.32, 2.23]
LHQ_eta_Q = [0.41, 0.823]

for i, (delta_iso, delta, eta_cs, CQ, eta_Q) in enumerate(zip(LHQ_delta_iso, LHQ_delta, LHQ_eta_cs, LHQ_CQ, LHQ_eta_Q)):
    LHQ_CS_tensor  = cs_tensor(delta_iso, delta, eta_cs)
    LHQ_Q_tensor = quad_tensor(CQ, eta_Q)
    print(f'--8HQ CS Tensor Cluster{i+1}:\n', LHQ_CS_tensor)
    print(f'--8HQ Quadrupolar Tensor Cluster{i+1}:\n', LHQ_Q_tensor)
    print('==============================')



--8HQ CS Tensor Cluster1:
 [[-20.4164   0.       0.    ]
 [  0.     -13.7436   0.    ]
 [  0.       0.       9.26  ]]
--8HQ Quadrupolar Tensor Cluster1:
 [[-0.6844  0.      0.    ]
 [ 0.     -1.6356  0.    ]
 [ 0.      0.      2.32  ]]
--8HQ CS Tensor Cluster2:
 [[ 20.5113   0.       0.    ]
 [  0.      -6.0813   0.    ]
 [  0.       0.     -41.43  ]]
--8HQ Quadrupolar Tensor Cluster2:
 [[-0.197355  0.        0.      ]
 [ 0.       -2.032645  0.      ]
 [ 0.        0.        2.23    ]]


In [4]:
#Input values for --8HQ (CASTEP)

HQ_delta_iso = 83.9663
HQ_delta = -8.53103
HQ_eta_cs = 0.47135
HQ_CQ = 2.09927
HQ_eta_Q = 0.9977


HQ_CS_tensor  = cs_tensor(HQ_delta_iso, HQ_delta, HQ_eta_cs)
HQ_Q_tensor = quad_tensor(HQ_CQ, HQ_eta_Q)
print(f'8HQ CS Tensor (CASTEP):\n', HQ_CS_tensor)
print(f'8HQ Quadrupolar Tensor (CASTEP):\n', HQ_Q_tensor)
print('==============================')


8HQ CS Tensor (CASTEP):
 [[90.2423655  0.         0.       ]
 [ 0.        86.2212645  0.       ]
 [ 0.         0.        75.43527  ]]
8HQ Quadrupolar Tensor (CASTEP):
 [[-0.00241416  0.          0.        ]
 [ 0.         -2.09685584  0.        ]
 [ 0.          0.          2.09927   ]]


**Rotation Angles for Computed Tensor**

In [11]:
#find eigenvalues and eigenvectors of original matrix
eigenvalues, eigenvectors = np.linalg.eig(HQ_CS_tensor) 

#CASTEP CS tensor (symmetric part)
HQ_CS_rot = np.zeros((3,3))                              #rotated CS tensor
HQ_CS_rot[0,0] = 90.0440; HQ_CS_rot[0,1] = -0.1909; HQ_CS_rot[0,2] = -1.44775;
HQ_CS_rot[1,0] = -0.1909; HQ_CS_rot[1,1] = 83.7563; HQ_CS_rot[1,2] = -4.55995;
HQ_CS_rot[2,0] = HQ_CS_rot[0,2]; HQ_CS_rot[2,1] = HQ_CS_rot[1,2]; HQ_CS_rot[2,2] = 78.0996
print('Rotated HQ_CS Tensor (Symmetric Part): \n', HQ_CS_rot)

eigenvalues_rot, eigenvectors_rot = np.linalg.eig(HQ_CS_rot)
print('\n Eigenvalues of rotated tensor: \n', eigenvalues_rot)
print('\n Eigenvectors of rotated tensor: \n', eigenvectors_rot)

R_T = np.matmul(eigenvectors_rot, np.linalg.inv(eigenvectors))
print("\n Calculated Rotation matrix:")
print(R_T,'\n')

b = np.degrees(np.arccos(R_T[2,2]))
a = np.degrees(np.arctan(R_T[2,1]/R_T[2,0]))
g = np.degrees(np.arctan(-R_T[1,2]/R_T[0,2]))
print("Calculated Euler angles (degrees):")
print(a, b, g,'\n')

Rotated HQ_CS Tensor (Symmetric Part): 
 [[90.044   -0.1909  -1.44775]
 [-0.1909  83.7563  -4.55995]
 [-1.44775 -4.55995 78.0996 ]]

 Eigenvalues of rotated tensor: 
 [75.43561656 90.2426726  86.22161084]

 Eigenvectors of rotated tensor: 
 [[-0.09272008 -0.98673827  0.13323127]
 [-0.48015389 -0.07291098 -0.87414886]
 [-0.87227016  0.14502266  0.46702591]]

 Calculated Rotation matrix:
[[-0.09272008 -0.98673827  0.13323127]
 [-0.48015389 -0.07291098 -0.87414886]
 [-0.87227016  0.14502266  0.46702591]] 

Calculated Euler angles (degrees):
-9.439588055000517 62.15858539997459 81.3340946391414 

